import { profilePhotoUri } from './images';

export const dummyProfiles = [
  {
    username: 'sevketaydogdu',
    realName: 'Sevket Aydogdu',
    avatar: profilePhotoUri,
    bio: 'React Native Developer | Expo Enthusiast 🚀',
    followers: 1250,
    following: 340,
    posts: 42,
    joinDate: 'March 2011',
  },
  {
    username: 'johndoe',
    realName: 'John Doe',
    avatar: 'https://i.pravatar.cc/300?img=1',
    bio: 'Tech enthusiast and blogger 📱',
    followers: 890,
    following: 410,
    joinDate: 'March 2011',
    posts: 28,
  },
  {
    username: 'janesmith',
    realName: 'Jane Smith',
    avatar: 'https://i.pravatar.cc/300?img=2',
    bio: 'Photographer & Traveler 📷✈️',
    followers: 1430,
    following: 500,
    joinDate: 'March 2011',
    posts: 35,
  },
  {
    username: 'techinsider',
    realName: 'Tech Insider',
    avatar: 'https://i.pravatar.cc/300?img=3',
    bio: 'Latest Tech News & Trends 🔥',
    followers: 5000,
    following: 200,
    joinDate: 'March 2011',
    posts: 150,
  },
  {
    username: 'gamingcentral',
    realName: 'Gaming Central',
    avatar: 'https://i.pravatar.cc/300?img=4',
    bio: '🎮 Daily Gaming Updates!',
    followers: 7000,
    following: 350,
    joinDate: 'March 2011',
    posts: 210,
  },
  {
    username: 'cryptoguy',
    realName: 'Crypto Guy',
    avatar: 'https://i.pravatar.cc/300?img=5',
    bio: 'Bitcoin to the moon 🚀💰',
    followers: 3200,
    following: 900,
    joinDate: 'March 2011',
    posts: 75,
  },
];
